version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres_pizzaria
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - ./data:/var/lib/postgresql/data
